# Site Settings
locale       : "en-US"
title        : "Ziyue Zhou"
description  : "Ph.D. Candidate in Law, The University of Hong Kong"
url          : https://zhouziyue233.github.io
baseurl      : ""

# Reading Files
include:
  - _pages
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - README.md
encoding     : "utf-8"
markdown_ext : "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown   : kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  entity_output: as_char
  smart_quotes: lsquo,rsquo,ldquo,rdquo

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: home

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed
